apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  serviceName: service
  replicas: 3
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
        selector: service
    spec:
      containers:
        - name: service
          image: service
          ports:
            - containerPort: 3000
          startupProbe:
            failureThreshold: 15
            initialDelaySeconds: 10
            periodSeconds: 30
            tcpSocket:
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: service
spec:
  clusterIP: None
  selector:
    app: service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: service-port
